### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by guylepage3** [brunohbrito/awesome-github-stats#32]
There seems to be a CORS issue with the `.json` end point. I am simply using the end point as a reference for my GitHub README.md Stats. https://github.com/guylepage3

From issue #27.
>> @brunobritodev, your end point seems to be causing some CORS issues. Is there a way to expose your endpoints to be raw .json data?

>The new version #31  are allowing cors from any origin.

_Originally posted by @brunobritodev in https://github.com/brunobritodev/awesome-github-stats/issues/27#issuecomment-1496911880_

Here's a screencapture to show the issue

<img width="750" alt="Screenshot 2023-04-05 at 5 28 21 AM" src="https://user-images.githubusercontent.com/1711854/230080502-a44a89cd-bc1d-4792-a40e-dba057ed80c6.png">

**Comment by guylepage3** [comment]
My goal is to slow work towards creating an automated version of my stats for folks to use for their GItHub README.md's. https://github.com/guylepage3/guylepage3

**Comment by brunobritodev** [comment]
Hi @guylepage3,

The cors seems to be working now, it was a misconfiguration at azure app service.

![image](https://user-images.githubusercontent.com/7241156/230091603-63355c49-cec6-4351-a168-fc417ffcc946.png)

**Comment by brunobritodev** [comment]
Hi @guylepage3 ,

The cors seems to be working now. It was a misconfiguration at Azure App Service.

![image](https://user-images.githubusercontent.com/7241156/230093711-ca02b3f5-7a7a-4209-9605-9358697aa06f.png)

**Comment by guylepage3** [comment]
Thanks @brunobritodev
